log:
  level: debug
  disable_sentry: true

listener:
  addr: :8000

vault:
  endpoint: ""
  token: ""
  mount_path: ""
  secret_path: ""

eth_rpc:
  client: ""

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: rpc-wrapper-svc
  service_port: 80
